# -*- coding: utf-8 -*-
"""Practice ^_^.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYRMAaEtjxMg6l_sN37asqMMxEyTL--i

# Practice    
# Enjoy^_^

# 1. Python Flow Control

## 1. Write a Python program to find those numbers which are divisible by 7 and multiples of 5, between 1500 and 2700 (both included).
"""

numbers = []
for i in range(1500,2701):
  if i % 7 == 0 and i % 5 == 0:
    numbers.append(i)
print(numbers)

"""## 2. Write a Python program to guess a number between 1 and 9.
Note : User is prompted to enter a guess. If the user guesses wrong then the prompt appears again until the guess is correct, on successful guess, user will get a "Well guessed!" message, and the program will exit.
"""

import random
guess_number = int(random.randint(1,9))

trial = 0
while trial < 3:
  number = int(input("Guess number from 1 to 9: "))
  trial += 1

  if number == guess_number:
    print("Congratultions ^^ 3")
    break
  else:
     print(f"Try Again {trial}")

"""## 3. Write a Python program that prints all the numbers from 0 to 6 except 3 and 6.
Note : Use 'continue' statement.
Expected Output : 0 1 2 4 5

"""

for i in range(0,7):
  if i == 3 or i == 6:
    continue
  else:
    print(i, end=" ")

"""## 4. Write a Python program to construct the following pattern, using a nested for loop.
```
*
* *
* * *
* * * *
* * * * *
* * * *
* * *
* *
*
```
"""

for row in range(9):
  for col in range(5):
      if (  (col == 1 and row in [0, 8]) or
            (col == 2 and row in [0, 1, 7, 8]) or
            (col == 3 and row in [0, 1, 2, 6, 7, 8]) or
            (col == 4 and row in [0, 1, 2, 3, 5, 6, 7, 8])
         ):
          print(" ", end = " ")
      else:
        print("*", end = " ")
  print()

"""## 5. Write a Python program that accepts a word from the user and reverses it.


"""

word = input("enter any word: ")
print(word[::-1])

"""## 6. Write a Python program to count the number of even and odd numbers in a series of numbers
Sample numbers : numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)

Expected Output :

Number of even numbers : 4

Number of odd numbers : 5
"""

numbers = [1,2,3,4,5,6,7,8,9]
even_count = 0
odd_count = 0

for i in numbers:
  if i % 2 == 0:
    even_count += 1
  else:
    odd_count += 1

print(f"Number of even numbers = {even_count}")
print(f"Number of odd numbers = {odd_count}")

"""## 7. Write a Python program to print the the first alphabet pattern 'A-Z' in your name .
for example  Expected Output:


```
  ***                                                                   
 *   *                                                                  
 *   *                                                                  
 *****                                                                  
 *   *                                                                  
 *   *                                                                  
 *   *
```
"""

for row in range(7):
    for col in range(5):
        if ((row == 0 and (col == 1 or col == 2 or col == 3)) or
           (row == 1 and (col == 0 or col == 4)) or
           (row == 2 and (col == 0 or col == 4)) or
           (row == 3) or
           (row >= 4 and (col == 0 or col == 4))):
            print("*", end="")
        else:
            print(" ", end="")
    print()

"""## 8.  Write a Python program to construct the following pattern, using a nested loop number.
Expected Output:


``
1
22
333
4444
55555
666666
7777777
88888888
999999999
``
"""

for i in range(1,10):
  for j in range(i):
    print(i , end="")
  print(end=" ")

"""## 9. Write a Python program to create the multiplication table (from 1 to 10) of a number.
Expected Output:

Input a number: 6                                                       
6 x 1 = 6                                                               
6 x 2 = 12                                                              
6 x 3 = 18                                                              
6 x 4 = 24                                                              
6 x 5 = 30                                                              
6 x 6 = 36                                                              
6 x 7 = 42                                                              
6 x 8 = 48                                                              
6 x 9 = 54                                                              
6 x 10 = 60

"""

result = 1
number = int(input("enter number= "))

for num in range(1,11):
  result = number* num
  print(f"{number} * {num} = {result}")

"""## 10. Write a Python program to calculate the sum and average of n integer numbers (input from the user). Input 0 to finish."""

class calculator:
  def __init__(self,numbers):
    self.numbers = numbers

  def summ(self):
    total = 0
    for i in self.numbers:
      total += i
    return total

  def avr(self):
    if len(self.numbers) != 0:
      average = sum(self.numbers)/ len(self.numbers)
      return average
    else:
      return 0

numbers = []
while True:
  num = int(input("Enter number and if you want to finish enter 0: "))
  if num == 0:
    break
  numbers.append(num)

# object
calc1 = calculator(numbers)
print(f"sum of numbers = {calc1.summ()}")
print(f"average of numbers = {calc1.avr()}")

"""# 11-Python Program to Print the Fibonacci sequence

The Fibonacci numbers are the numbers in the following integer sequence. 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, …….. In mathematical terms, the sequence Fn of Fibonacci numbers is defined by the recurrence relation.


![image.png](attachment:image.png)
"""

def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)


n = int(input("Enter number= "))

print("Fibonacci")
for i in range(n):
    print(fibonacci(i), end=" ")

"""# 12. Simulating a Basic ATM Withdrawal"""

class ATM:
  def __init__(self, balance):
    self.balance= balance

  def withdraw(self,amount):
      if self.balance >= amount:
        self.balance -= amount
        print(f"withdraw done, your remaining balance = {self.balance}")
        return self.balance
      else:
        print("not enough money")

  def deposit(self, balance_amount):
    self.balance += balance_amount
    print(f"deposite done, your current balance = {self.balance}")
    return self.balance

balance = 50000
atm1 = ATM(balance)

print(f"your balance = {balance}")

while True:
  operation = input("Type \"w\" for withdraw and \"d\" for deposite and \"q\" for quit: ")
  if operation == "q":
      print("thank you")
      break

  match(operation):
    case "w":
      withdraw_amount = int(input("enter withdraw amount = "))
      atm1.withdraw(withdraw_amount)
    case "d":
      deposite_amount =  int(input("enter deposite amount = "))
      atm1.deposit(deposite_amount)
    case _:
      print("wrong operaton")
      break

"""# 13.Finding Common Elements in Two Lists"""

lst1 = [1,2,9,7,6]
lst2 = [6,7,4,9]

common_element = []
for e in lst1:
  if e in lst2:
    common_element.append(e)

print(f"common Element = {common_element}")

"""# 14. Calculating Factorial of a Number"""

def factorial(n):
  if n ==0 or n == 1:
    return 1
  else:
    return n * factorial(n-1)

number = int(input("enter the number to calculate factorial= "))
fact = factorial(number)
print(f"the factorial of {number}! is = {fact} ")

"""# 15. Finding the Sum of Digits of a Number"""

def sum_digits(num):
  total = 0
  for i in str(num):
    total += int(i)
  return total

number = int(input("enter number: "))
res = sum_digits(number)
print(res)